fields:
  - show
  - search
  - email
  - website
  - similar

development:
  redis_namespace: visitors_development
  redis_config:
    host: localhost

uat:
  redis_namespace: visitors_development
  redis_config:
    host: qa.touchlocal.com
